apiVersion: 1

datasources:
  - name: Zabbix
    type: alexanderzobnin-zabbix-datasource
    access: proxy
    url: http://127.0.0.1:8080/api_jsonrpc.php
    basicAuth: false
    isDefault: true
    jsonData:
      username: Admin
      password: zabbix
      trends: true
      trendsFrom: "7d"
      cacheTTL: "1h"
